### PR TITLE
ben.aubry_auth0_60be7cbc9d409a0069cd0f72-BondReference

### PR DESCRIPTION
**Pull request by regnosys-prod-user**

### CODE REVIEW

**Review by iansloyan — CHANGES_REQUESTED** [review]
Hi @ben-aubry thank you for your contribution - was there any benefit considered in this design to using the _Price_ type (or even _FixedRateSpecification_ type) instead of _number_ type?

**Comment by ben-aubry** [comment]
I think we could use _FixedRateSpecification_ type instead of number.

**Comment by iansloyan** [comment]
Sounds like a plan to me. Thanks @ben-aubry

**Comment by iansloyan** [comment]
superseded by https://github.com/finos/common-domain-model/pull/1999

**Pull request closed without merging**
