### PR TITLE
Add TripartyAgentEnum to PartyRoleEnum

### PR DESCRIPTION
**Pull request by tomhealey-icma**
Adding TripartyAgent to PartyRoleEnum.

### CODE REVIEW

**Review by chrisisla — CHANGES_REQUESTED** [review]
Comments please change "An third..." to "A third..." otherwise this is all good.

**Comment by iansloyan** [comment]
@tomhealey-icma Good addition - surprised it was not there already

@valdensmith do you think we could or should add "Third Party" to this change for completeness? https://www.isda.org/a/978ME/Triparty-vs.-Third-Party-8.12.19.pdf

**Comment by valdensmith** [comment]
This looks like an addition to the PartyRoleEnum list, where Tri Party Agent is a new one Tom has added correct? 
In that enumeration list there is already 'Custodian' which is not as specific and could mean a TriParty custodian or a third party custodian which have different roles. I am not against adding Tri Party Agent and its description, but users may get confused between the 2. Can @tomhealey-icma  confirm the use case to which the addition is required?

**Comment by valdensmith** [comment]
> @tomhealey-icma Good addition - surprised it was not there already
> 
> @valdensmith do you think we could or should add "Third Party" to this change for completeness? https://www.isda.org/a/978ME/Triparty-vs.-Third-Party-8.12.19.pdf

Responded in his conversion

**Comment by tomhealey-icma** [comment]
I hadn't considered the ThirdParty role and I can why it makes sense to add it as well since it acts in a different capacity. From what I understand a triparty agent should be a (I)CDS and maybe always is, but it's not clear if it must be a (I)CSD. 

So before adding the question is, should we use:
Triparty, TripartyAgent or TripartyCustodian and same for Thirdparty, ThirdpartyAgent or ThirpartyCustodian?

**Comment by tomhealey-icma** [comment]
For clarification, in the repo execution workflow all parties are attached to the trade object with their respective partyrole that is needed for sftr reporting, clearing and settlement:

Here's a settlement agent example:

                              {
                                    "partyReference": {
                                          "externalReference": "549300OZ46BRLZ8Y6F65",
                                          "globalReference": "6cb3f258"
                                    },
                                    "role": "SETTLEMENT_AGENT"
                              }

**Comment by tomhealey-icma** [comment]
Based on market terminology I'm proposing to add:

	TripartyAgent <"A third party entity that acts as an intermediary and provides automated clearing, settlement, allocation, valuation and reporting services.">
	ThirdPartyCustodian <"A third-party providing custody, settlement, segregation and reporting services.">

**Comment by valdensmith** [comment]
All good for me now

**Review by valdensmith — APPROVED** [review]

**Review by chrisisla — APPROVED** [review]

**Comment by lolabeis** [comment]
Please provide release notes in .md format as a comment in the PR before it is merged, so that notes can be added to the release tag.

You can follow these guidelines:
https://cdm.docs.rosetta-technology.io/source/contribution.html#content-of-release-notes

**Pull request merged**
