### PR TITLE
Jan Baserba Commodity Delivery Options

### PR DESCRIPTION
**Pull request by regnosys-prod-user**

### CODE REVIEW

**Comment by JanBaserba** [comment]
Issue #2465

**Comment by JanBaserba** [comment]
LABELS
Category: Modelling
Complexity: Minor Change
Criticallity: High
Target: Development

**Comment by JanBaserba** [comment]
Release notes:

[commodity_delivery_options_release_notes.md](https://github.com/finos/common-domain-model/files/13113624/commodity_delivery_options_release_notes.md)

**Review by tomhealey-icma — CHANGES_REQUESTED** [review]
The title say Commodity Delivery Options but there are 40 files of changes that include other changes. It would need to be cleaned up before review.

**Pull request closed without merging**
