### PR TITLE
Bataller García Eric Zero-Strike Swaps qualification and mappings

### PR DESCRIPTION
**Pull request by davidalk**

### CODE REVIEW

**Review by tomhealey-icma — CHANGES_REQUESTED** [review]
Can you explain why this adds a duplicate type, PrincipalPaymentSchedule (0..1)  with a different attribute name, principalPaymentDescriptions, and the description doesn't seem to align with the attributes of PrincipalPaymentSchedule. Also please add the proper labels to the PR.

**Comment by ebataller** [comment]
@tomhealey-icma Yes I added principalPaymentDescriptions with a different attribute name, to differenciate it from the existing principalPaymentSchedule, because these attributes can reuse the same type but they are representing quite different elements from FpML.
The new attribute principalPaymentDescriptions is representing the principalExchangeDescriptions inside a returnSwap (in FpML), while principalPaymentSchedule is representing the cashflows in a swapStream.
I thought that it could be useful to have this difference, to avoid confusion and also to be able to check and update the existing mapper more easily after this release, but it can be deleted and use the same attribute name on both.
The description was initially added following the description of the element principalExchangeDescriptions from FpML, it can be modified to fit CDM properly.

**Comment by ebataller** [comment]
Hello, @finos-admin

Please add the following labels to both this PR and issue [#2266](https://github.com/finos/common-domain-model/issues/2266), linked to this PR.

Minor Enhancement/Change
Category: Modelling
Criticality: Medium
Complexity: Low
Target: Development

**Comment by PayalKhanna** [comment]
@ebataller could you add Release Note for this change on the PR please

**Review by tomhealey-icma — APPROVED** [review]
Reviewed responses and looks good.

**Comment by PayalKhanna** [comment]
please close this PR 
22/08 -> All the work on zero-strike equity swaps is paused until a clearer requirement on this topic emerges either from a CDM implementer pointing to a functional gap in the product model or from a trade sample that can be confidently used to pinpoint the functional gap to bridge

**Pull request closed without merging**
