### PR TITLE
Lucía Cortés CapacityUnitEnum 6x

### PR DESCRIPTION
**Pull request by regnosys-prod-user**

### CODE REVIEW

**Comment by LuciaCortesTH** [comment]
Issue: https://github.com/finos/common-domain-model/issues/3196

**Review by manel-martos — DISMISSED** [review]
Accepted at Nov 5th FINOS CDM Contribution Review

**Comment by JayasriR** [comment]
@LuciaCortesTH Can you please add release notes for this. thanks

**Comment by JayasriR** [comment]
@LuciaCortesTH Can you please provide release notes for this change. thanks

**Comment by LuciaCortesTH** [comment]
Here you have the Release Notes for both PR:
https://github.com/finos/common-domain-model/pull/3198 and
https://github.com/finos/common-domain-model/pull/3197

Thank you,

Lucía Cortés

**Comment by PayalKhanna** [comment]
@LuciaCortesTH The link on you comment doesn't show any RN can you attach a .md file on the PR please or paste the RN details as comment
Thanks

**Comment by LuciaCortesTH** [comment]
@PayalKhanna Hello Payal, I replied via email, but the RN didn’t upload in the comment—sorry about that. Here they are (they’re the same for both capacity unit enums in the PR). I’ve also added the RN in the PR comments alongside the issue link, not just in the original issue. Thank you! 
[RN_CapacityUnitEnum.md](https://github.com/user-attachments/files/17716081/RN_CapacityUnitEnum.md)

**Review by dshoneisda — APPROVED** [review]

**Pull request merged**
