### PR TITLE
Roger Guitart RogerGuitart-ETD-Positions-Contribution

### PR DESCRIPTION
**Pull request by regnosys-prod-user**

### CODE REVIEW

**Review by tomhealey-icma — CHANGES_REQUESTED** [review]
There are a number of issues with want is being proposed and what was previously added. The position type attribute priceQuantity does not define the price treatment, is it FIFO, LIFO, Ave Cost, ...). There is also an attribute trade reference that allows max of 1, why would there not be more? Regarding the new additions, a position is not an extension of a ContractBase and parties are not attached to positions, only through the trades that make up the position. I would request that this topic be presented to the CRWG with a deck with scenarios such as a trading book position and fund holding for starters.

**Comment by rogerguitart** [comment]
Issue #2471

**Comment by rvincentISDA** [comment]
Good catch on tradeReference. The design was also pointing to an unbounded optional list. Roger has adjusted.
The MVP is centered around the EMIR Refit use case. It is not the objective to build a full position management model  but rather represent the information that all the SMEs of the DPBE and the ETD Taskforce have agreed as minimum for this first pass. It is indeed agreed that other price features, treatment and other aspect will be needed and the design has remained open to that.  Let 's touch based early next week on your other points.

**Comment by rogerguitart** [comment]
Release Notes: 
[ETD_Positions_ReleaseNotes.md](https://github.com/finos/common-domain-model/files/13251973/ETD_Positions_ReleaseNotes.md)

**Review by rvincentISDA — DISMISSED** [review]

**Review by tomhealey-icma — DISMISSED** [review]

**Comment by PayalKhanna** [comment]
PR with updated expectations: https://github.com/finos/common-domain-model/pull/2510

**Comment by hugohills-regnosys** [comment]
Closing PR as it has merge issues.  Will recontribute and add a link to the new PR for reference

**Pull request closed without merging**
