### PR TITLE
Gerard Opazo Trigger type refactoring [Prod] release HOLD MERGE

### PR DESCRIPTION
**Pull request by PayalKhanna**
original Contribution https://github.com/finos/common-domain-model/pull/2879

### CODE REVIEW

**Comment by PayalKhanna** [comment]
Issue https://github.com/finos/common-domain-model/issues/2849

**Comment by PayalKhanna** [comment]
approved in https://github.com/finos/common-domain-model/pull/2879#pullrequestreview-2033818803

**Review by eacunaISDA — APPROVED** [review]

**Comment by PayalKhanna** [comment]
@gopazoTH @dshoneisda can you review expectations changes please there are increase in validation failures

**Comment by gopazoTH** [comment]
Hi @PayalKhanna I have mitigated the validation errors both for prod and dev, I've seen you regenerated the expectations in dev, now they are looking good, so I have approved dev PR. 
When you generate now the expectations for prod we should be able to see no validation errors anymore, I will approve once it gets generated and everithing looks as expected.

**Comment by PayalKhanna** [comment]
@gopazoTH updated expectations

**Review by gopazoTH — APPROVED** [review]
everything looking fine

**Pull request closed without merging**
