### PR TITLE
Roger Guitart CommodityClassificationMappings_DEV

### PR DESCRIPTION
**Pull request by regnosys-prod-user**

### CODE REVIEW

**Comment by rogerguitart** [comment]
Linked to issue #2706

**Comment by rogerguitart** [comment]
To add the following 2 FpML samples under `fpml-5-13 / processes`:
[CommodityClassification_FpML_Files.zip](https://github.com/finos/common-domain-model/files/14385109/CommodityClassification_FpML_Files.zip)

**Comment by rogerguitart** [comment]
Release Notes: 
[CommodityClassification_ReleaseNotes.md](https://github.com/finos/common-domain-model/files/14407853/CommodityClassification_ReleaseNotes.md)

**Comment by PayalKhanna** [comment]
superseded by https://github.com/finos/common-domain-model/pull/2735

**Pull request closed without merging**
