### PR TITLE
Jan Baserba Commodity Delivery Part 1

### PR DESCRIPTION
**Pull request by regnosys-prod-user**

### CODE REVIEW

**Review by tomhealey-icma — CHANGES_REQUESTED** [review]
The diffs show a large number of changes to the contractualProduct template although it's not clear what the actual changes are because there are many lines are the same but moved or edited slightly. I suggest a meeting with contributors to review.

**Comment by JanBaserba** [comment]
Issue:

https://github.com/finos/common-domain-model/issues/2344

**Comment by JanBaserba** [comment]
Labels:
Minor Enhancement/Change
Category: Modelling
Criticality: High
Complexity: Medium
Target: Development

**Comment by rvincentISDA** [comment]
This PR should be closed given it has been resubmitted under PR https://github.com/finos/common-domain-model/pull/2372 to avoid the previous diff issues observed on github

**Pull request closed without merging**
