### PR TITLE
Roger Guitart Roger Guitart Exchange Traded Derivative

### PR DESCRIPTION
**Pull request by regnosys-prod-user**

### CODE REVIEW

**Comment by PayalKhanna** [comment]
replaced with https://github.com/finos/common-domain-model/pull/2302

**Comment by chrisisla** [comment]
Hi @PayalKhanna, 
From your previous comment this PR has been replaced by #2302, is it okay to close this PR now then?
Thanks, Chris

**Comment by PayalKhanna** [comment]
Yes

Sent from Samsung Mobile on O2
Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by chrisisla** [comment]
Cool, thanks for confirming @PayalKhanna, closing this PR now

**Pull request closed without merging**
