### PR TITLE
CreditSeniorityEnum mappings

### PR DESCRIPTION
**Pull request by minesh-s-patel**
Added CreditSeniorityEnum synonym

### CODE REVIEW

**Review by iansloyan — APPROVED** [review]
As this is only a change to FpML mappings file - good to approve. 

Can I ask if the scheme was updated recently at all? Or was this just never mapped?
I see this enum has a scheme related to it
[docReference ISDA FpML_Coding_Scheme schemeLocation "http://www.fpml.org/coding-scheme/credit-seniority"]

**Comment by ebataller** [comment]
### Release Notes

**Background**

An issue was found recently with the mapping for the EMIR field `2.143 - Seniority`. This release adds the necessary enumeration CreditSeniorityEnum in tradestate.synonym to fix the issue.

**What is being released?**

_Enumerations_

- Added mapping coverage for EMIR field `2.143 - Seniority` by adding `CreditSeniorityEnum` enumeration in tradestate.synonym.

_Samples_

- Added 3 new Credit samples to test the mapping for EMIR field `2.143 - Seniority`:
cdindex-ex01-cdx-seniority-Senior.xml
cdindex-ex02-cdx-seniority-Subordinate.xml
cdindex-ex03-cdx-seniority-Other.xml

**Review directions**

In the CDM Portal, select Translate and review the following samples:

fpml-5-10/products/credit

cdindex-ex01-cdx-seniority-Senior.xml
cdindex-ex02-cdx-seniority-Subordinate.xml
cdindex-ex03-cdx-seniority-Other.xml

**Comment by ebataller** [comment]
*Samples pending to be added on Monday

**Comment by hugohills-regnosys** [comment]
> ### Release Notes

@ebataller note that these release notes do not conform to the guidelines, see [here](https://cdm.docs.rosetta-technology.io/source/contribution.html#content-of-release-notes).  I have updated the title, and formatting.

**Comment by ebataller** [comment]
# *Product Model - FpML synonym mappings for CreditSeniorityEnum*

_Background_

This release updates and extends the FpML mapping coverage for the product model.

_What is being released?_

- FpML mappings added for enum `CreditSeniorityEnum`
- FpML samples added to test the synonym mappings

_Review directions_

In the CDM Portal, select Ingestion and review the following samples in the test pack:

  - fpml-5-10 > products > credit > cdindex-ex01-cdx-seniority-Senior.xml
  - fpml-5-10 > products > credit > cdindex-ex02-cdx-seniority-Subordinate.xml
  - fpml-5-10 > products > credit > cdindex-ex03-cdx-seniority-Other.xml

**Pull request merged**
