### PR TITLE
Benjamin AUBRY InflationSwaps_FinalPrincipalExchangeCalculation 

### PR DESCRIPTION
**Pull request by regnosys-prod-user**

### CODE REVIEW

**Comment by ben-aubry** [comment]
This PR replaces https://github.com/finos/common-domain-model/pull/2127

**Comment by chrisisla** [comment]
Hi @ben-aubry, 
Are you okay for me to close #2127 as it is now replaced by this PR?
Thanks!

**Comment by ben-aubry** [comment]
Hi @chrisisla, yes I am ok if https://github.com/finos/common-domain-model/pull/2127 gets closed.
Thank you very much !

In the meantime, can this PR be approved please ?

**Review by iansloyan — APPROVED** [review]

**Comment by iansloyan** [comment]
the relevant changes were made to principalexchange to have it as an enum; I assume then that InflationCalculationStyleEnum is sufficiently specific to inflation that the prefix Inflation is relevant?

**Pull request merged**
