### PR TITLE
BondReference_couponRate

### PR DESCRIPTION
**Pull request by PayalKhanna**
BondReference_couponRate - Changing the data type from FixedRateSpecification to number

### CODE REVIEW

**Comment by tomhealey-icma** [comment]
Please respond to comments or withdraw this PR.

**Comment by ben-aubry** [comment]
@iansloyan, apologies for the late reply on this. The rationale for the couponRate being a number is to match with the FpML structure (please see the below screenshot). 

Screen Shot 2023-07-19 at 2 05 04 PM

**Comment by ben-aubry** [comment]
Also, @iansloyan , would my changes carry over to version 5.0.0 ?

**Comment by ben-aubry** [comment]
Hello @iansloyan  - would you have any update on the above ?

**Comment by dshoneisda** [comment]
@ben-aubry can this please be closed if #2313 replaces it

**Comment by iansloyan** [comment]
replaced by https://github.com/finos/common-domain-model/pull/2313

**Pull request closed without merging**
