### PR TITLE
Scheme Import to replace /n/t to clean up description text

### PR DESCRIPTION
**Pull request by PayalKhanna**

### CODE REVIEW

**Review by hugohills-regnosys — DISMISSED** [review]

**Comment by PayalKhanna** [comment]
close

**Comment by PayalKhanna** [comment]
reopen

**Comment by PayalKhanna** [comment]
close

**Comment by PayalKhanna** [comment]
reopen

**Comment by PayalKhanna** [comment]
close

**Comment by PayalKhanna** [comment]
reopen

**Review by hugohills-regnosys — APPROVED** [review]

**Pull request merged**
