### PR TITLE
JEAN BAPTISTE ZIADE minorFixforPortfolioSwap

### PR DESCRIPTION
**Pull request by regnosys-prod-user**

### CODE REVIEW

**Comment by JBZ-Fragmos** [comment]
main reason for this PR is to correct 2 inconsistencies that result in rejection of trade file due to errors below
in both cases, the root issue is that prior condition is having unexpected impact on attributes included in the "extended" scope

**1st issue :**
- **validationStr**,Validation FAILURE on [WorkflowStep.businessEvent.instruction(0).primitiveInstruction.execution.product.contractualProduct.economicTerms.payout.performancePayout(0).underlier.basket] for [DATA_RULE] [BasketOneOf0] because [One and only one field must be set of 'basketConstituent', 'portfolioBasketConstituent', 'productTaxonomy', 'productIdentifier'. Set fields are 'basketConstituent', 'productIdentifier'.]
  - **definition**,one-of
  - BUSINESS ISSUE = this is preventing for instance to define productIdentifier for a Basket _because_ basketConstituent exists in the basket, etc.

**2nd issue :**
- **validationStr**,Validation FAILURE on [WorkflowStep.businessEvent.instruction(0).primitiveInstruction.execution.product.contractualProduct.economicTerms.payout.performancePayout(0).portfolioReturnTerms(0)] for [DATA_RULE] [ReturnTermsReturnTermsExists] because [[[dividendReturnTerms, priceReturnTerms]] should only be set.  Set fields: [payerReceiver, quantity, dividendReturnTerms, initialValuationPrice, underlier, priceReturnTerms]]
  - **definition**,if priceReturnTerms -> returnType = ReturnTypeEnum -> Total then (priceReturnTerms, dividendReturnTerms) only exists else if priceReturnTerms -> returnType = ReturnTypeEnum -> Price then priceReturnTerms only exists else priceReturnTerms only exists or dividendReturnTerms only exists or varianceReturnTerms only exists or volatilityReturnTerms only exists or correlationReturnTerms only exists
  -   - BUSINESS ISSUE = this is preventing for instance to define any of the new components released as portfolioReturn leg attributes (e.g. payerReceiver, quantity, dividendReturnTerms, initialValuationPrice, underlier)

for avoiding the **1st issue**, here is the **related change** with this PR : 
image

for avoiding the **2nd issue**, here is the **related change** with this PR : 
image
hopefully using of "optional choice" as below shall permit to ensure there is mutually exclusive choices between
- priceReturnTerms and other _else than_ dividendTerms, 
- as well as between dividendReturnTerms and other _else than_ priceReturnTerms
- while permitting to have both priceReturnTerms and dividendReturnTerms to exist when relevant

**Comment by JBZ-Fragmos** [comment]
by the way have also updated cardinality of objects which are metadata address pointing on location with distinct cardinality (i mean referencing should be aligned in terms of cardinality e.g. if location object is card (0..*) then address object should by default (unless particular reason not to do so) have same cardinality - hence 2 changes about ti that you will also find inside the PR

**Comment by dshoneisda** [comment]
@lolabeis please can you/your team review this update?

**Comment by lolabeis** [comment]
> @lolabeis please can you/your team review this update?

Yes we'll add it to the next sprint (starting next week)

**Comment by lolabeis** [comment]
Hi @JBZ-Fragmos Thank you for submitting your PR. I have taken a look and I _think_ I understand the problem you're trying to solve.

This problem arises because of how conditions of correlated existence or absence (`one-of`, `required choice`, `only-exists` etc) are interpreted in the context of an extended type. My overarching comment is that we should look to formalise (and possibly amend) that interpretation in the DSL.
Fyi @hugohills @SimonCockx 

On the details of your PR:

1. The fix looks fine, although it points to a potential difference in interpretation between `one-of` and `required choice` in that case, which we need to investigate.
2. The fix is more problematic in this case, because it modifies (relaxes) the behaviour of `ReturnTerms`, which we don't want. I can think of a couple of alternative approaches that would avoid such side-effect - e.g. having `ReturnTerms` as an encapsulated type in `PortfolioReturnTerms` instead of using `extends`.
3. Cardinality. Not related to the above, alignment makes sense.

**Comment by JBZ-Fragmos** [comment]
@lolabeis thanks for this first feedback, 

as regards 2., normally had tried to replicate exactly same level of constraints, not to have any relaxing effect... kindly clarify which condition would be relaxed exactly with current PR proposal compared to existing model ? i'm fine with any good suggestions you may propose in this regards, since i'm not an expert about condition dratfing, but i would like for my knowledge to better understand where i might have missed something

all in all i understand you will provide further feedbacks soon, thanks for that, and do not hesitate to get me involved if i can help in any manner

**Comment by lolabeis** [comment]
@JBZ-Fragmos 
As discussed at the [CDM Derivatives Products and Business Events Working Group - May 22nd, 2024](https://github.com/finos/common-domain-model/issues/2905), please re-submit with changes for 1 and 3 only

**Comment by JBZ-Fragmos** [comment]
@Leo ***@***.***> just done ! thanks

[A screenshot of a computer  Description automatically generated]

Rgds
JB

**Review by lolabeis — DISMISSED** [review]
Approved - Changes accord with comments submitted at the [CDM Derivatives Products and Business Events Working Group - May 22nd, 2024](https://github.com/finos/common-domain-model/issues/2905)

**Comment by lolabeis** [comment]
@JBZ-Fragmos Can you please provide release notes at your earliest, as a comment in your PR. Changes have been approved for imminent release in CDM 5.13.

**Comment by JBZ-Fragmos** [comment]
## RELEASE NOTE ##
**Product Model - fix for Portfolio Return Terms**

_Background_

Purpose is to correct one blocking error related to condition, and minor fix about cardinality of some components, embedded with past release of Portfolio Return Terms.

_What is being released?_

- updated condition attached to **Basket**, now as _condition: **required choice** basketConstituent, portfolioBasketConstituent_ (instead of previously _condition: **one-of**_)
- updated the cardinality of **PerformancePayout** attribute below, now (**0..***) 
  (instead of (**0..1**) previously) : 
  - **initialValuationPrice**, 
  - **interimValuationPrice** 
  - and **finalValuationPrice**
- updated the cardinality of **PortfolioReturnTerms** attribute below, now (**0..***)
  (instead of (**0..1**) previously) : 
  - quantity
  - **initialValuationPrice**
  - **interimValuationPrice** 
  - and **finalValuationPrice**

_Review directions_

In the Rosetta platform, select the Textual Browser and inspect the change identified above.
The changes can be reviewed in PR 2910

**Comment by JBZ-Fragmos** [comment]
Done !

Thanks

[A screenshot of a computer  Description automatically generated]

**Comment by JayasriR** [comment]
superceded by https://github.com/finos/common-domain-model/pull/2978

**Pull request closed without merging**
