### PR TITLE
Gerard Opazo Enhanced Price mappings

### PR DESCRIPTION
**Pull request by regnosys-prod-user**

### CODE REVIEW

**Comment by gopazoTH** [comment]
Release notes:
[knownAmountSchedule_mappings_update_release_notes.md](https://github.com/finos/common-domain-model/files/13831596/knownAmountSchedule_mappings_update_release_notes.md)

**Comment by gopazoTH** [comment]
**Labels**:

Category: Modelling
Complexity: Small/Bug/Mapping
Criticality: Low
Target: Development

**Comment by gopazoTH** [comment]
image
The attached pic shows how the mappings for knownAmountSchedule work for IR IRS FixedFloat ZC KnownAmount sample that is in DRR and has been coverted into confirmation sample for CDM testing purposes.

**Comment by PayalKhanna** [comment]
Superseded with https://github.com/finos/common-domain-model/pull/2630

**Pull request closed without merging**
