### PR TITLE
Changes to utilize the new Python code generator (v2)

### PR DESCRIPTION
**Pull request by dschwartznyc**
[Category: Technical/Patch](https://github.com/finos/common-domain-model/labels/Category%3A%20Technical%2FPatch)
[Complexity: Minor Change](https://github.com/finos/common-domain-model/labels/Complexity%3A%20Minor%20Change)
[Criticality: Medium/Low](https://github.com/finos/common-domain-model/labels/Criticality%3A%20Medium%2FLow)
[Target: Production](https://github.com/finos/common-domain-model/labels/Target%3A%20Production)
dependencies: [generators PR #290](https://github.com/REGnosys/rosetta-code-generators/pull/290)

Authors: CloudRisk (@plamen-neykov), TradeHeader (@manel-martos, @dcarrascosa00), FT Advisory (@dschwartznyc)

_What is being released?_
This release uses the new version of the Python generator (v2) which includes the following changes:

- Migration to Pydantic 2.x
- More comprehensive support for Rosetta's operators
- Resolves the defect exposed by [PR 2766](https://github.com/finos/common-domain-model/pull/2766)
- Includes an update to the Python Rosetta runtime library used to encapsulate the Pydantic support (now version 2.0.0)

changes:
* codefresh.yml: uses new rosetta runtime, cleanup of build, and expansion of Python unit tests
* rosetta-source/pom.xml: changed to use new Python rosetta runtime library
* rosetta-source/test/python: new and updated Python unit tests
* release.md

### CODE REVIEW

**Comment by dschwartznyc** [comment]
Note that the failed build is a result of the dependency on the deployment of the new generator for which there is an outstanding PR.

**Comment by minesh-s-patel** [comment]
> Note that the failed build is a result of the dependency on the deployment of the new generator for which there is an outstanding PR.

Thanks @dschwartznyc 

This PR is dependent of the Rosetta (Rune) code generators PR: https://github.com/REGnosys/rosetta-code-generators/pull/290. We are in the process of reviewing this and will provide feedback directly on the PR.

**Review by dshoneisda — DISMISSED** [review]

**Comment by minesh-s-patel** [comment]
@dschwartznyc 

I have released your rosetta-code-generators change.
See https://github.com/REGnosys/rosetta-code-generators/releases/tag/10.15.8

Can you please update the pom.xml to update the "rosetta-bundle" to `10.15.8`. 
I think you will get a green build with that!

**Comment by dschwartznyc** [comment]
> @dschwartznyc 
> 
> 
> 
> I have released your rosetta-code-generators change.
> 
> See https://github.com/REGnosys/rosetta-code-generators/releases/tag/10.15.8
> 
> 
> 
> Can you please update the pom.xml to update the "rosetta-bundle" to `10.15.8`. 
> 
> I think you will get a green build with that!

Done.

**Review by minesh-s-patel — DISMISSED** [review]

**Comment by minesh-s-patel** [comment]
> > @dschwartznyc
> > I have released your rosetta-code-generators change.
> > See https://github.com/REGnosys/rosetta-code-generators/releases/tag/10.15.8
> > Can you please update the pom.xml to update the "rosetta-bundle" to `10.15.8`.
> > I think you will get a green build with that!
> 
> Done.

Green build! Well done.

**Review by minesh-s-patel — APPROVED** [review]

**Pull request merged**
