### PR TITLE
Marc Gratacos Minor updates to the Zero Coupon Qualification

### PR DESCRIPTION
**Pull request by regnosys-prod-user**

### CODE REVIEW

**Comment by mgratacos** [comment]
Labels
Category: Modeling
Complexity: Minor Change
Criticality: Low
Target: Development

**Comment by mgratacos** [comment]
Issue #2592

**Comment by mgratacos** [comment]
[release_notes_ZC_qual_updates.md](https://github.com/finos/common-domain-model/files/13715294/release_notes_ZC_qual_updates.md)

**Review by dshoneisda — APPROVED** [review]

**Comment by JayasriR** [comment]
Superseded by https://github.com/finos/common-domain-model/pull/2648

**Pull request closed without merging**
