### PR TITLE
Jan Baserba FRO Mappings Update

### PR DESCRIPTION
**Pull request by regnosys-prod-user**

### CODE REVIEW

**Comment by JanBaserba** [comment]
Issue: #2596

**Comment by JanBaserba** [comment]
Release notes: 
[fro_mappings_update_release_notes.md](https://github.com/finos/common-domain-model/files/13740803/fro_mappings_update_release_notes.md)

**Comment by JanBaserba** [comment]
**Labels:**

Category: Modelling
Complexity: Small/Bug/Mapping
Criticality: Low
Target: Development

**Review by tomhealey-icma — DISMISSED** [review]

**Comment by PayalKhanna** [comment]
superseded with https://github.com/finos/common-domain-model/pull/2633

**Pull request merged**
