### PR TITLE
Jan Baserba Commodity Delivery Part 2

### PR DESCRIPTION
**Pull request by regnosys-prod-user**

### CODE REVIEW

**Comment by JanBaserba** [comment]
Related Issue: #2412

**Comment by JanBaserba** [comment]
Labels:

Category: Modelling
Complexity: Minor Change
Criticality: High
Target: Development
Rosetta

**Comment by JanBaserba** [comment]
Release notes:
[commodity_delivery_2_release_notes.md](https://github.com/finos/common-domain-model/files/12767770/commodity_delivery_2_release_notes.md)

**Comment by PayalKhanna** [comment]
Superseded https://github.com/finos/common-domain-model/pull/2437

**Review by rvincentISDA — APPROVED** [review]

**Review by tomhealey-icma — CHANGES_REQUESTED** [review]
The diffs should get fixed first.

**Review by rvincentISDA — APPROVED** [review]

**Comment by PayalKhanna** [comment]
@tomhealey-icma can you review this PR please

**Pull request closed without merging**
