### PR TITLE
Manuel Carrera RBA_BOND_BASIS DCF Prod

### PR DESCRIPTION
**Pull request by regnosys-prod-user**

### CODE REVIEW

**Comment by manucarreramoreno** [comment]
# Product Model - Day Count Fraction: RBA_Bond_Basis

_Background_

The codes `RBA_BOND_BASIS_QUARTER`, `RBA_BOND_BASIS_SEMI_ANNUAL` and `RBA_BOND_BASIS_ANNUAL` in the CDM enum `DayCountFractionEnum` have been found redundant by definition. The solution to this issue is to merge them into one single code: `RBA_BOND_BASIS`. This also aligns with the FpML representation.

_What is being released?_

* Replaced the codes `RBA_BOND_BASIS_QUARTER`, `RBA_BOND_BASIS_SEMI_ANNUAL` and `RBA_BOND_BASIS_ANNUAL` with the code `RBA_BOND_BASIS` in the CDM enum `DayCountFractionEnum`.

* Mapping added to populate the new code with the FpML code `RBA`.

_Review directions_

* In the CDM Portal, select the Textual Browser and inspect each of the changes identified above.

**Review by lolabeis — COMMENTED** [review]
@manucarreramoreno This PR contains backward-incompatible changes, so cannot go against Prod. In your Prod PR you should introduce the new enum value but mark the other ones as "deprecated" (through a comment rather than the applicable annotation, because the latter doesn't work for enum values)

Also the release notes should not mention the "CDM Portal" (decomm'ed).

**Comment by manucarreramoreno** [comment]
@lolabeis I have commited the change fixing backward-incompatibility

On the release notes, should I mention anything instead of the CDM portal?

**Review by lolabeis — APPROVED** [review]
The release notes should be adjusted to reflect the fact that the other 3 DCF are only deprecated, not removed.

**Comment by PayalKhanna** [comment]
superseded https://github.com/finos/common-domain-model/pull/2726

**Comment by Oblongs** [comment]
Reviewed and approved in the [CDM Derivatives Products and Business Events Working Group - February 27th, 2024](https://github.com/finos/common-domain-model/issues/2669#top)

**Pull request merged**
