### PR TITLE
Jan Baserba Commodity Delivery 1 reupload

### PR DESCRIPTION
**Pull request by regnosys-prod-user**

### CODE REVIEW

**Review by tomhealey-icma — CHANGES_REQUESTED** [review]
As discussed on the CRWG please resubmit a clean version so we can review the actual changes. Also, the LocationIdentifierTypeEnum is a generic description applied to a specific list of commodity transportation locations. I suggest the name is change CommodityLocationIndentiferTypeEun.

**Comment by JanBaserba** [comment]
[commodity_delivery_1_release_notes.md](https://github.com/finos/common-domain-model/files/12537728/commodity_delivery_1_release_notes.md)

**Comment by JanBaserba** [comment]
Issue: #2344

**Comment by rvincentISDA** [comment]
This PR can be closed given a new version has been submitted: [2380](https://github.com/finos/common-domain-model/pull/2380)

**Comment by lolabeis** [comment]
Closing as superseded by #2380

**Pull request closed without merging**
