### PR TITLE
Roger Guitart AmericanExercise condition update

### PR DESCRIPTION
**Pull request by regnosys-prod-user**

### CODE REVIEW

**Comment by rogerguitart** [comment]
Linked to Issue #2913

**Comment by rogerguitart** [comment]
# _Product Model - Modification of AmericanExercise Condition in ExerciseTerms_
_Background_

The conditions under `ExerciseTerms` in the refactored `OptionPayout` are not sufficiently restrictive for the american options. More specifically, the `AmericanExercise` condition should not only control that the `expirationDate` is present (which it already does through the `CommencementAndExpirationDate` condition), but that it is also **present only once** (not currently implemented in the model). This release aims at modifying the `AmericanExercise` condition to correct this.

_What is being released?_

- The `AmericanExercise` condition under the `ExerciseTerms` type has been modified to constraint the `expirationDate` field to only one occurrence.

_Review directions_

In the Rosetta Platform, select the Textual View and inspect the change identified above.

**Review by mgratacos — APPROVED** [review]

**Review by chrisisla — APPROVED** [review]

**Comment by lolabeis** [comment]
For audit trail:
Approved at the [CDM Derivatives Products and Business Events Working Group - May 8th, 2024](https://github.com/finos/common-domain-model/issues/2897)

**Comment by lolabeis** [comment]
@mgratacos @rogerguitart This PR was merged prematurely:
* The PR should have contained an update to the RELEASE.md file, in accordance with the note provided, and the note itself should get approved.
* The PR contains a backward-incompatible change (making a condition stricter). Even though it should not impact actual implementations, it should still be noted as such in the release note.

Please resubmit a new PR with the RELEASE.md updated and get it approved, otherwise this change cannot be released.

**Pull request merged**
