### PR TITLE
Ebataller isdaiifm tma master agreement type enum release prod

### PR DESCRIPTION
**Pull request by PayalKhanna**
original PR https://github.com/finos/common-domain-model/pull/2696

### CODE REVIEW

**Comment by PayalKhanna** [comment]
Issue: https://github.com/finos/common-domain-model/issues/2695

**Comment by PayalKhanna** [comment]
approved in https://github.com/finos/common-domain-model/pull/2696

**Comment by PayalKhanna** [comment]
Labels
Category: Modelling
Complexity: Small
Criticality: Low/Medium
Target: Production

**Review by eacunaISDA — DISMISSED** [review]

**Review by Oblongs — APPROVED** [review]
Reviewed and approved in the [CDM Derivatives Products and Business Events Working Group - February 27th, 2024](https://github.com/finos/common-domain-model/issues/2669#top)

**Review by hugohills-regnosys — APPROVED** [review]

**Comment by hugohills-regnosys** [comment]
Build failed due to bad gateway, not code issues

**Pull request merged**
