### PR TITLE
Website changes

### PR DESCRIPTION
**Pull request by eteridvalishvili**

### CODE REVIEW

**Comment by maoo** [comment]
Pasting here the error message from Netlify...

```
Error: Image ../docs/img/CDM–Build-Release-Process.png used in ../docs/contribution.md not found.
```

The file `docs/FINOS-CDM-Governance-Structure.png` should go in the `website/static/img` folder and the href should be `/img/CDM–Build-Release-Process.png`

**Comment by eteridvalishvili** [comment]
Hi @maoo The FINOS-CDM-Governance-Structure.png file is not for the website but for fixing a broken link in the Readme.md. Is there a different file I should put it in, or is it okay to include it in the website static images if it's only meant for the Readme?

**Comment by maoo** [comment]
> Hi @maoo The FINOS-CDM-Governance-Structure.png file is not for the website but for fixing a broken link in the Readme.md. Is there a different file I should put it in, or is it okay to include it in the website static images if it's only meant for the Readme?

You're right @eteridvalishvili , the issue was on another path, my bad; I committed a change to your PR and it seems that it's working now 😄

**Review by dshoneisda — APPROVED** [review]
The governance diagram put back in is the wrong one and needs updating.
All the other changes are good though, so I will approve and merge, but send you an email note to remake the governance diagram change

Thanks

**Pull request merged**
