### PR TITLE
Add executionDateTime to Execution Details

### PR DESCRIPTION
**Pull request by tomhealey-icma**
ExecutionDetails type currently does not include an execution date and time, and Trade type only includes date type. This is needed for various regulatory reports and booking systems.

### CODE REVIEW

**Comment by nigelcobb** [comment]
@tomhealey-icma this issue was discussed at a special session of the DRR Working Group a few weeks ago.
It would be useful to refer back to those materials as the conclusion reached at that discussion is not in line with your proposal.
The regulatory specific concept is served through the DRR model.  An Execution BusinessEvent has a timestamp associated with the WorkflowStep that creates that event so the Core CDM was also felt to be sufficiently expressive.

**Comment by tomhealey-icma** [comment]
Thanks, @nigelcobb for the feedback but my view is that a trade is representative of an event and the attribute tradeDate date (1..1) is insufficient to capture what is a legal and regulatory element of that event. Most regulations today require date, time in microseconds and timezone. Rather than modify trade date I suggest adding zonedDateTime to execution details.

**Comment by chrisisla** [comment]
I think this warrants a bit more conversation. 

I've only had a brief look but if you use Create_BusinessEvent for an execution then I don't think you get back an execution date/time. As Tom suggests it is a requirement for a lot of regulations (and applications) these days that the date, time to the ms and the timezone are all reported, but I don't see you get that currently from this function.

If you used WorkflowStep instead then there is an EventTimeStamp in it, but you'd have to use the WorkflowStep functions to get that returned...

Realistically we should consider how we can get the date/time/timezone returned back for any transaction during a trade lifecycle, not just for the initial execution (I think this is required for MiFID?). If the recommendation is that we always use the WorkflowStep functions so that "timestamp" can be used then we need to consider how this will impact existing usage of the Create_BusinessEvent function.

So in general I am more aligned with Tom on this, I think a generic zonedDateTime element (i.e. not just for executions) within the BusinessEvent itself would be beneficial.

@tomhealey-icma , @nigelcobb  - thoughts?

**Comment by tomhealey-icma** [comment]
Just adding to my earlier notes, when thinking about the trade date/time it should not be the same as when a business event or workflow event took place. A workflow event is when something took place in the workflow process, but that may not be the same as the trade date/time as agreed by the counterparties which I believe becomes part of the trade contract.

**Pull request closed without merging**
