### PR TITLE
JEAN BAPTISTE ZIADE PortfolioPriceReturnTerms_PRODUCT

### PR DESCRIPTION
**Pull request by regnosys-prod-user**

### CODE REVIEW

**Comment by JBZ-Fragmos** [comment]
related Issue with description
https://github.com/finos/common-domain-model/issues/2745

for more details, 
please refer to documentation attached as part of Agena for DPBE 2024-Feb-27

**Comment by lolabeis** [comment]
Thanks @JBZ-Fragmos.

I believe you also want that contribution to hit **CDM Prod** (i.e. currently version `5.6`) so that it's usable in DRR, don't you? This means that you will need to submit a separate PR from a workspace that is based off version `5.6`.

**Comment by JBZ-Fragmos** [comment]
@lolabeis in regards of your last cooment above _"you will need to submit a separate PR from a workspace that is based off version 5.6."_

- actually i have no more WS free to do this, because i already use 3 WS
- also do not know technically how to "select" which version i mean even if i could have enough WS i do not see how to decide which version it is based on
- all in all, i'm pleased to help the best i can but honestly, it looks like you are asking me to copy/paset all items manually from WS to another one ? looks havy process for me, really... can't you just handle this at your end e.g. duplicate my PR and push it to the correct version for Prod/DRR, please ?

**Comment by lolabeis** [comment]
@JBZ-Fragmos
Just a reminder that you also need to port your latest set of PROD changes to this DEV Pull Request (using the same workspace you used for that contribution). However in this one, you'll be able to relax the backward-compatibility constraint and execute the further refactoring you initially proposed.

**Comment by lolabeis** [comment]
Superseded by #2934

**Pull request closed without merging**
