### PR TITLE
STORY-3216: Enhanced Contractual party mappings 

### PR DESCRIPTION
**Pull request by hugohills-regnosys**

### CODE REVIEW

**Comment by gopazoTH** [comment]
Issue #2788

**Comment by gopazoTH** [comment]
Labels:

Category: Modelling
Complexity: Small/Bug/Mapping
Criticality: Low
Target: Production

**Comment by gopazoTH** [comment]
RN:
[contractualParty-mappings.md](https://github.com/finos/common-domain-model/files/14726211/contractualParty-mappings.md)

**Comment by hugohills-regnosys** [comment]
Replaced by https://github.com/finos/common-domain-model/pull/2809

**Pull request closed without merging**
