### PR TITLE
Windows build added to github workflows

### PR DESCRIPTION
**Pull request by tomhealey-icma**
This PR will add windows build to github actions.

### CODE REVIEW

**Comment by tomhealey-icma** [comment]
Windows build added to workflows. Please approve.

**Comment by minesh-s-patel** [comment]
> Windows build added to workflows. Please approve.

@tomhealey-icma 
You have added a "windows-latest" version to the CVE scanning workflow. This will run the scanning on windows so wont run the full build on Windows. E.g. a test that does not work on Windows will not be picked up by this. Was this the intention?

**Comment by tomhealey-icma** [comment]
No this is not intentional. I added the following recommended changes to a separate .yml file but the build failed. Do you have ay suggestions:
name: CDM Build on Windows machine
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Maven install
        run: mvn install

**Comment by tomhealey-icma** [comment]
I added a new file windows-build.yml and it appears to be working now. Please review and approve.

**Comment by SimonCockx** [comment]
Hi @tomhealey-icma, can you please also revert your changes to the CVE scanning workflow?

Thanks for the contribution by the way. As a Windows user myself this will make things easier. :)

**Comment by SimonCockx** [comment]
Oh, and don't you also need to [specify a trigger](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#using-events-to-trigger-workflows) for the workflow? E.g., `on: [push, pull_request]`.

**Comment by maoo** [comment]
@tomhealey-icma - your last change has an invalid syntax, seehttps://github.com/finos/common-domain-model/actions/runs/6235368056

I'd suggest to remove lines from 5 to 19.

Also, as @SimonCockx suggested above, I'd revert changes to `cve-scanning.yml`

**Comment by maoo** [comment]
@tomhealey-icma - last commit broke the action, but before that, the action run successfully, see https://github.com/finos/common-domain-model/actions/runs/6236542330/job/16928091815

Could you please revert your last commit?

**Comment by tomhealey-icma** [comment]
I reverted back to the "working version" but getting a failure on push process and cdm build. It's not clear if this is due to a problem with the yml or building on windows. Any thoughts?

**Comment by maoo** [comment]
> I reverted back to the "working version" but getting a failure on push process and cdm build. It's not clear if this is due to a problem with the yml or building on windows. Any thoughts?

Interesting; I see a successful run on https://github.com/finos/common-domain-model/actions/runs/6237892710/job/16932508095 , but on the same code change, I see a failure on https://github.com/finos/common-domain-model/actions/runs/6237892689

The failure is this:
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Common Domain Model 0.0.0.master-SNAPSHOT:
[INFO] 
[INFO] Common Domain Model ................................ FAILURE [01:17 min]
[INFO] rosetta-source ..................................... SKIPPED
[INFO] rosetta-project .................................... SKIPPED
[INFO] tests .............................................. SKIPPED
[INFO] examples ........................................... SKIPPED
[INFO] distribution ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:28 min
[INFO] Finished at: 2023-09-19T15:47:45Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal on project cdm-parent: Could not resolve dependencies for project org.finos.cdm:cdm-parent:pom:0.0.0.master-SNAPSHOT: Failed to collect dependencies at com.regnosys.rosetta:com.regnosys.rosetta:jar:8.6.2 -> org.eclipse.emf:org.eclipse.emf.ecore.xcore.lib:jar:1.6.0 -> org.eclipse.xtext:org.eclipse.xtext.xbase.lib:jar:2.30.0-SNAPSHOT: Failed to read artifact descriptor for org.eclipse.xtext:org.eclipse.xtext.xbase.lib:jar:2.30.0-SNAPSHOT: Could not transfer artifact org.eclipse.xtext:org.eclipse.xtext.xbase.lib:pom:2.30.0-SNAPSHOT from/to regnosys-artifactory-snapshots (https://regnosys.jfrog.io/regnosys/libs-snapshot): authentication failed for https://regnosys.jfrog.io/regnosys/libs-snapshot/org/eclipse/xtext/org.eclipse.xtext.xbase.lib/2.30.0-SNAPSHOT/org.eclipse.xtext.xbase.lib-2.30.0-SNAPSHOT.pom, status: 401 Unauthorized -> [Help 1]
```

See https://github.com/finos/common-domain-model/actions/runs/6237892689/job/16932508114#step:4:2265

To avoid this issue, I'd suggest removing any reference to `regnosys-artifactory`, but I remember that @minesh-s-patel was already working on it; is there any update there?

**Comment by tomhealey-icma** [comment]
All the tests passed. Please approve.

**Review by maoo — APPROVED** [review]
Lgtm

**Pull request merged**
