### PR TITLE
Marc Gratacos Support for ETDs: ListedDerivative & deliveryTerm

### PR DESCRIPTION
**Pull request by regnosys-prod-user**

### CODE REVIEW

**Comment by mgratacos** [comment]
Category: Modelling
Complexity: Minor Change
Critically: High
Target: Development

**Comment by mgratacos** [comment]
This PR addresses the following issue: https://github.com/finos/common-domain-model/issues/2299

**Comment by lolabeis** [comment]
> This PR addresses the following issue: #2299

@mgratacos I have now linked the PR to the issue using the "Development" section on the left-hand side panel. This is the correct way to link a PR to an issue, and means that the issue will automatically get closed once the PR is merged.

**Comment by mgratacos** [comment]
[release_notes_etd_20230906 (1).md](https://github.com/finos/common-domain-model/files/12537474/release_notes_etd_20230906.1.md)

**Comment by mgratacos** [comment]
[release_notes_etd_20230906.md](https://github.com/finos/common-domain-model/files/12537480/release_notes_etd_20230906.md)

**Review by rvincentISDA — APPROVED** [review]

**Review by rvincentISDA — APPROVED** [review]

**Review by chrisisla — APPROVED** [review]

**Pull request merged**
