### PR TITLE
Bataller García Eric PTRR - Portfolio Rebalancing 

### PR DESCRIPTION
**Pull request by davidalk**

### CODE REVIEW

**Comment by davidalk** [comment]
Original PR #2531

**Review by ebataller — APPROVED** [review]

**Review by hugohills-regnosys — APPROVED** [review]

**Review by hugohills-regnosys — DISMISSED** [review]

**Review by chrisisla — CHANGES_REQUESTED** [review]
I don't think this is the correct use of the ```intent```. There has been a lot of discussion about how to use ```intent``` and the usage here is more about the purpose of an execution i.e. the intent of this ```businessEvent``` is an execution, the _reason_ for performing the execution is to rebalance the portfolio but the intention is still an execution.

**Comment by mgratacos** [comment]
> I don't think this is the correct use of the `intent`. There has been a lot of discussion about how to use `intent` and the usage here is more about the purpose of an execution i.e. the intent of this `businessEvent` is an execution, the _reason_ for performing the execution is to rebalance the portfolio but the intention is still an execution.

The primitiveInstruction is Execution but the event is a Portfolio Rebalancing event. It is equivalent to a primitiveInstruction Execution for a Novation business event or for a Clearing business event.

The use of Intent is documented in CDM as: The intent attribute is meant to be specified when the event qualification cannot be programmatically inferred from the event features. 

This is exactly the case for Portfolio Rebalancing event that is supported by an Execution primitive instruction.

ESMA is identifying Portfolio Rebalancing and Portfolio Compression as Post-Trade Risk Reduction events. These events are reportable for EMIR reporting.

**Comment by chrisisla** [comment]
Thanks for the clarification @mgratacos. I know we're trying to reduce the reliance on ```intent``` but your explanation makes sense.

**Review by chrisisla — APPROVED** [review]

**Pull request merged**
