### PR TITLE
Roger Guitart SettlementType_Mappings_PROD

### PR DESCRIPTION
**Pull request by regnosys-prod-user**

### CODE REVIEW

**Comment by rogerguitart** [comment]
Linked to issue #2698

**Comment by rogerguitart** [comment]
Release Notes: 
[SettlementTypeMappingFix_ReleaseNotes.md](https://github.com/finos/common-domain-model/files/14377428/SettlementTypeMappingFix_ReleaseNotes.md)

**Comment by PayalKhanna** [comment]
superseded https://github.com/finos/common-domain-model/pull/2728

**Comment by Oblongs** [comment]
Reviewed and approved in the [CDM Derivatives Products and Business Events Working Group - February 27th, 2024](https://github.com/finos/common-domain-model/issues/2669#top)

**Pull request closed without merging**
