### PR TITLE
Bataller García Eric ISDAIIFM_TMA value for Master Agreement Type - Dev

### PR DESCRIPTION
**Pull request by regnosys-prod-user**

### CODE REVIEW

**Comment by ebataller** [comment]
Labels
Category: Modelling
Complexity: Small
Criticality: Low/Medium
Target: Development

**Comment by ebataller** [comment]
# _Master Agreement Type enumeration - ISDAIIFM_TMA code_

In CDM there is not any available codes for Islamic Master Agreements.  This contribution adds a new `ISDAIIFM-TMA` code to the `MasterAgreementTypeEnum` to cover the Islamic Derivative Master Agreements in CDM.

_What is being released?_

- Added a new `ISDAIIFM_TMA` code to the MasterAgreementTypeEnum.
- Mapping coverage for this new `ISDAIIFM_TMA` code.

_Review directions_

In the CDM Portal, select the Textual Browser and inspect each of the changes identified above.

**Comment by ebataller** [comment]
Issue: [#2695](https://github.com/finos/common-domain-model/issues/2695)

Labels
Category: Modelling
Complexity: Small
Criticality: Low/Medium
Target: Development

**Comment by PayalKhanna** [comment]
Superseded https://github.com/finos/common-domain-model/pull/2718

**Comment by PayalKhanna** [comment]
superseded by https://github.com/finos/common-domain-model/pull/2724

**Pull request closed without merging**
