### PR TITLE
Update use-cases.md

### PR DESCRIPTION
**Pull request by vallslaura**
Updated documentation, @PayalKhanna, solved issues.

### CODE REVIEW

**Comment by vallslaura** [comment]
@chrisisla Now the section is in the right order! Thank you!

**Review by chrisisla — APPROVED** [review]
Beautiful! Thank you!

**Comment by PayalKhanna** [comment]
@vallslaura build failed

**Comment by vallslaura** [comment]
@PayalKhanna All checks have passed now, build failure has been solved.

**Pull request merged**
