### PR TITLE
ben.aubry_auth0_60be7cbc9d409a0069cd0f72-InflationSwaps

### PR DESCRIPTION
**Pull request by regnosys-prod-user**

### CODE REVIEW

**Review by iansloyan — COMMENTED** [review]
Hi @ben-aubry thank you for adding this content and suggesting this contribution.
I think this works (my initial comment was - should this be added to InflationRateSpecification - but I then saw you have added it)
Can I ask for the provenance of the enumerated values? Are they published in any standards anywhere that we can reference?

**Comment by ben-aubry** [comment]
Hi @iansloyan, the enumerated values come from the FpML schema itself. Please see this [link] for calculationMethod(https://www.fpml.org/spec/fpml-5-12-4-rec-1/html/confirmation/schemaDocumentation/schemas/fpml-ird-5-12_xsd/complexTypes/InflationRateCalculation/calculationMethod.html) and this [link] for calculationStyle (https://www.fpml.org/spec/fpml-5-12-4-rec-1/html/confirmation/schemaDocumentation/schemas/fpml-ird-5-12_xsd/complexTypes/InflationRateCalculation/calculationStyle.html)

**Review by jonnance — DISMISSED** [review]

**Review by chrisisla — DISMISSED** [review]

**Comment by ben-aubry** [comment]
**Inflation Swaps - calculationMethod + calculationStyle**

**Background:**
This release adds the following fields:

- calculationMethod. This field will be added as an enum value. The enum will contain the following values:
- Ratio
- Return
- Spread

- calculationStyle. This field will be added as an enum value. The enum will contain the following values: 
- YearOnYear
- ZeroCoupon

These fields can be found under the following paths:
- For calculationMethod, please use - InterestRatePayout > rateSpecification > inflationRate > calculationMethod
- For calculationStyle, please use - InterestRatePayout > rateSpecification > inflationRate > calculationStyle

The enum values can be found under the following paths:
- For calculationMethod, a new enum called "InflationCalculationMethodEnum" was added. This can be found at rosetta-source/src/main/rosetta/observable-asset-calculatedrate-enum.rosetta

- For calculationStyle, a new enum called "InflationCalculationStyleEnum" was added. This can be found at rosetta-source/src/main/rosetta/observable-asset-calculatedrate-enum.rosetta 

**Testing:**
In the CDM Portal, select the Textual Browser and inspect each of the changes identified above.

**Comment by iansloyan** [comment]
@ben-aubry 

Can you check the release note fits these contribution release note format?
https://cdm.docs.rosetta-technology.io/source/contribution.html#content-of-release-notes

Once that is done we are good to release as @chrisisla has also approved with me

**Review by iansloyan — DISMISSED** [review]
subject to release notes conforming with 
https://cdm.docs.rosetta-technology.io/source/contribution.html#content-of-release-notes

We have 2 approvals from ISDA and ISLA maintainers which is sufficient to release

**Comment by tomhealey-icma** [comment]
I'm aware that the enum references used are aligned with FpML but I would suggest that instead of carry "Inflation..." forward to the enum types that the more generic CalculationMethodEnum be expanded to include the new types. Also in reference to the use of Style since the reference is to the index base why not call it IndexBase. A broad descriptor is less specific in it purpose unless Style included other enums not related to IndexBase. I'm am neither approving or requesting a change but as we worked to establish principles and style in the CDM this is one example.

**Comment by iansloyan** [comment]
> * calculationStyle

I actually think you are right on calculationMethodEnum - I just thought keeping this separate would be preferred. But open to suggesting expanding that enum and using that.

Re the suggestion on IndexBase, I think what you you are referencing is found as an attribute indexStyle of type FloatingRateIndexStyleEnum but it is very tied to the ISDA definition of a floating rate option. Again I would be open to exploring a more generic solution.

**Review by hugohills-regnosys — APPROVED** [review]

**Pull request merged**
