### PR TITLE
Gerard Opazo Qualifying functions where underlier is ETD Prod

### PR DESCRIPTION
**Pull request by regnosys-prod-user**

### CODE REVIEW

**Comment by gopazoTH** [comment]
Issue #2683

**Review by lolabeis — APPROVED** [review]

**Comment by lolabeis** [comment]
@gopazoTH The release notes should not mention the CDM Portal (decomm'ed)

**Comment by PayalKhanna** [comment]
supercedded by https://github.com/finos/common-domain-model/pull/2733

**Comment by Oblongs** [comment]
Reviewed and approved in the [CDM Derivatives Products and Business Events Working Group - February 27th, 2024](https://github.com/finos/common-domain-model/issues/2669#top)

**Pull request closed without merging**
