### PR TITLE
Georgina Tarres TH_Valuation_Instruction

### PR DESCRIPTION
**Pull request by regnosys-prod-user**

### CODE REVIEW

**Comment by gtarres** [comment]
Linked to ISSUE #2543  

### Release notes:
[CDM_release_notes_Valuation.md](https://github.com/finos/common-domain-model/files/13502637/CDM_release_notes_Valuation.md)

### Proposed labels:
Category: Modelling
Complexity: Minor change
Criticality: Medium/Low
Target: Developement

**Comment by gtarres** [comment]
Required review from @lolabeis. To be added in the prod release.

**Review by tomhealey-icma — CHANGES_REQUESTED** [review]
I don't believe the addition of a valuation object should constitute a change in trade state. I would suggest adding ValuationState without replicating history before to after on every change.

**Comment by lolabeis** [comment]
@tomhealey-icma in response to your comments:

> I don't believe the addition of a valuation object should constitute a change in trade state.

The `TradeState` object was introduced specifically to separate information that **does not** change the `Trade` object (cashflows, observations), but which may nonetheless impact a trade, from information that **does** change the `Trade` object (any sort of amendment).

In an extension of this design, valuation was added to `TradeState` as part of an earlier approved change. It follows that changing / updating it means changing the `TradeState` object, a role that is currently fulfilled by a `Primitive`. The change proposed in this PR is consistent with the current design.

> I would suggest adding ValuationState without replicating history before to after on every change.

Can you clarify your suggestion, keeping in mind that any change must be backward-compatible? What would be the difference between `ValuationState` and `Valuation`, and would `ValuationState` be included in `TradeState`?

**Review by lolabeis — APPROVED** [review]

**Review by tomhealey-icma — APPROVED** [review]
Although this is not a lifecycle event change and shouldn't necessitate a tradeState change this can go ahead for 5.0 but should be revisited in 6.0.

**Review by eacunaISDA — APPROVED** [review]

**Pull request merged**
