### PR TITLE
JEAN BAPTISTE ZIADE BespokePayoutFormula

### PR DESCRIPTION
**Pull request by regnosys-prod-user**

### CODE REVIEW

**Comment by JBZ-Fragmos** [comment]
@lolabeis @Oblongs @mgratacos 

that is draft at this stage, however already kindly ask **feedback** to **confirm this PR is "backward-compatible"** ?

for clarity, i'm not asking for now feedback about content of objects per se, etc. because there will be some minor adjustments to come, and anyway the PPT Support Documentation is not yet ready, etc. 
but it is important and will save lot of time if you could already perform a check on this particular angle of view i.e. do you find any issue for compatibility or is it effectively backward compatible, as intended

thanks a lot in advance for any help in that matter
do not hesitate if any question

JB

**Comment by JBZ-Fragmos** [comment]
related GitHub Issue for description is this one : 
https://github.com/finos/common-domain-model/issues/2941

**Comment by Oblongs** [comment]
> do you find any issue for compatibility or is it effectively backward compatible, as intended

I believe there may be a problem with the renaming of the attributes `pricingTime` and `pricingTimeType` in `ObservationTerms`.  This would force a change on existing code.

**Comment by JBZ-Fragmos** [comment]
@Oblongs 
thanks a lot for your feedback, about renaming of the attributes _pricingTime_ and _pricingTimeType_ in ObservationTerms. 

 then **will _push back_ the related changes**

**Comment by JBZ-Fragmos** [comment]
## cancelled / replaced by # https://github.com/finos/common-domain-model/pull/3128

**Comment by JBZ-Fragmos** [comment]
# cancelled / replaced by https://github.com/finos/common-domain-model/pull/3128

**Pull request closed without merging**
