### PR TITLE
Ankit Kulkarni Add spreadCalculationMethodEnum

### PR DESCRIPTION
**Pull request by regnosys-prod-user**

### CODE REVIEW

**Comment by iansloyan** [comment]
@ankitkulkarni1 per the discussion on https://github.com/finos/common-domain-model/pull/2151 can you generalise the comment as spreadCalculationMethod may be used for other purposes
The suggestion was to say "Method by which spread is calculated. For example on an asset swap: "par-par" or "proceeds" may be the method indicated."

**Comment by ankitkulkarni1** [comment]
@iansloyan I've addressed your comments in my latest commit. Please review and let me know if any other changes are necessary. Thanks!

**Review by iansloyan — DISMISSED** [review]
Thank you for making the changes

**Review by chrisisla — DISMISSED** [review]

**Review by iansloyan — APPROVED** [review]
approving after conflict resolved

**Review by minesh-s-patel — APPROVED** [review]

**Pull request merged**
