### PR TITLE
Gerard Opazo Trigger type refactoring [Prod]

### PR DESCRIPTION
**Pull request by regnosys-prod-user**

### CODE REVIEW

**Comment by gopazoTH** [comment]
Issue #2849

**Review by dshoneisda — COMMENTED** [review]
Approved per DPBE 24th April, ratified for release at CRWG 1st May

**Comment by mgratacos** [comment]
This PR should be merged to DEV of the next major version of CDM since it breaks backward compatibility.

**Comment by gopazoTH** [comment]
# Product Model - Refactoring of level and levelPercentage within Trigger CDM

**_Background_**:

Currently, `level` and `levelPercentage` represent the Trigger values for specific elements such as barriers. The interest in having them represented as Price types is strong since it is a richer type than a number.

**_What is being released?_**

A refactoring of '`level` and `levelPercentage` within Trigger CDM to a unified CDM element `level` of type PriceSchedule.

_Data types:_

- Updated `Trigger` type with a new unified `level` element of `PriceSchedule` type.
- The condition `Choice1` has been updated to be consistent with the proposal.
- Modification of the synonym mappings for `Trigger` type.

**_Review directions:_**

In the Rosetta Platform, select the Textual View and inspect each of the changes identified above.

The changes can be reviewed in PR: #2879.

**Comment by PayalKhanna** [comment]
Superseded by https://github.com/finos/common-domain-model/pull/2927

**Pull request closed without merging**
