### PR TITLE
Jan Baserba Commodity Delivery (second resubmission)

### PR DESCRIPTION
**Pull request by regnosys-prod-user**

### CODE REVIEW

**Comment by JanBaserba** [comment]
Issue: https://github.com/finos/common-domain-model/issues/2344

**Comment by JanBaserba** [comment]
[commodity_delivery_1_release_notes.md](https://github.com/finos/common-domain-model/files/12550396/commodity_delivery_1_release_notes.md)

**Review by rvincentISDA — DISMISSED** [review]

**Review by tomhealey-icma — CHANGES_REQUESTED** [review]
The LocationIdentifierTypeEnum is a generic description applied to a specific list of commodity transportation locations. I suggest the name is change CommodityLocationIndentiferTypeEnum.

**Comment by rvincentISDA** [comment]
@tomhealey-icma The LocationIdentifierTypeEnum  has been updated per your suggestion I think.

**Review by tomhealey-icma — DISMISSED** [review]
I'll approve this on he expectation that the changes will be made.

**Comment by PayalKhanna** [comment]
@tomhealey-icma 
there are no expectation changes for this can you please review this 
Thanks

**Review by rvincentISDA — APPROVED** [review]

**Pull request merged**
