### PR TITLE
Commodity product mappings

### PR DESCRIPTION
**Pull request by minesh-s-patel**
This contribution enhances the product representation for commodities

### CODE REVIEW

**Comment by manucarreramoreno** [comment]
[Release-Notes-CommodityMappings.md](https://github.com/finos/common-domain-model/files/11063207/Release-Notes-CommodityMappings.md)

**Comment by iansloyan** [comment]
How does this change the CDM model? I only see changes to the Synonym (FpML) files - is that correct? No changes to any other (model namespace?) files. This distinction in describing what has been done will probably speed up approval (i.e. if the only changes are in FpML mapping synonym files.)

**Comment by rvincentISDA** [comment]
Where do I see the correct release note ? The file uploaded in this conversation carries a title different from the content. The programmatic syntax seems off as well.

**Comment by iansloyan** [comment]
is this superseded by 2067?

**Comment by manucarreramoreno** [comment]
> Where do I see the correct release note ? The file uploaded in this conversation carries a title different from the content. The programmatic syntax seems off as well.

Sorry about that, Ruddy. The correct Release Notes have now been uploaded to PR 2067

**Pull request closed without merging**
