### PR TITLE
index names place holder

### PR DESCRIPTION
**Pull request by PayalKhanna**
original contribution #2335

### CODE REVIEW

**Review by winitall01 — APPROVED** [review]
changes inline with expectations

**Comment by lolabeis** [comment]
> changes inline with expectations

What is the driver for the validation failure increase?

**Comment by winitall01** [comment]
> > changes inline with expectations
> 
> What is the driver for the validation failure increase?

Hello @lolabeis - the expectation errors occured due to a require choice clause between index name and id. we've modified it now.

**Review by lolabeis — COMMENTED** [review]
The release note needs to be changed to reflect what has been implemented. `IndexReferenceInformation` is not, in fact, a new type. It already existed, but the problem was that it contained all the information related to a credit index. So your work was to split it into two and create a more basic `IndexReferenceInformation` type that could be encapsulated within a rate option. The release notes also need to mention `CreditIndexReferenceInformation` and how it's been implemented as an extension.

**Review by lolabeis — COMMENTED** [review]
@winitall01 Please proceed with this PR following today's conversation between CDM maintainers. The release note still needs to be adjusted as per my earlier comment.

**Review by iansloyan — APPROVED** [review]
Approved based on other issues being addressed in future

**Review by chrisisla — DISMISSED** [review]

**Review by hugohills-regnosys — APPROVED** [review]

**Pull request merged**
