### PR TITLE
Roger Guitart CommodityClassificationMappings_PROD

### PR DESCRIPTION
**Pull request by regnosys-prod-user**

### CODE REVIEW

**Comment by rogerguitart** [comment]
Linked to issue #2706

**Comment by rogerguitart** [comment]
To add the following 2 FpML samples under `fpml-5-13 / processes`:
[CommodityClassification_FpML_Files.zip](https://github.com/finos/common-domain-model/files/14385112/CommodityClassification_FpML_Files.zip)

**Review by lolabeis — APPROVED** [review]
@rogerguitart Do we have any test pack sample that would illustrate the mapping change?

**Comment by rogerguitart** [comment]
> @rogerguitart Do we have any test pack sample that would illustrate the mapping change?

@lolabeis Not in CDM Core. I believe the two examples I am proposing (ex69 and ex70) in the earlier comment are present in DRR, but not in CDM. By adding these 2 FpML samples, we'll have commodity classification covered both in DRR and CDM Core.

**Comment by lolabeis** [comment]
@rogerguitart 
> By adding these 2 FpML samples, we'll have commodity classification covered both in DRR and CDM Core.
Those are record-keeping samples, which we only position in DRR. Let's keep consistent and not add anything in CDM now.

**Comment by rogerguitart** [comment]
Release Notes: 
[CommodityClassification_ReleaseNotes.md](https://github.com/finos/common-domain-model/files/14407867/CommodityClassification_ReleaseNotes.md)

**Comment by PayalKhanna** [comment]
Superseded by https://github.com/finos/common-domain-model/pull/2734

**Pull request merged**
